language:
  - objective-c

env:
  - NODE_VERSION="7",CBTR_TEST="eslint-unit-tests-cov"
  - NODE_VERSION="6",CBTR_TEST="eslint-unit-tests-cov"
  - NODE_VERSION="5",CBTR_TEST="eslint-unit-tests-cov"
  - NODE_VERSION="4",CBTR_TEST="eslint-unit-tests-cov"
  - NODE_VERSION="7",CBTR_TEST="integration-tests"
  - NODE_VERSION="6",CBTR_TEST="integration-tests"
  - NODE_VERSION="5",CBTR_TEST="integration-tests"
  - NODE_VERSION="4",CBTR_TEST="integration-tests"
  - NODE_VERSION="7",CBTR_TEST="functional-tests"
  - NODE_VERSION="6",CBTR_TEST="functional-tests"
  - NODE_VERSION="5",CBTR_TEST="functional-tests"
  - NODE_VERSION="4",CBTR_TEST="functional-tests"

branches:
  only:
  - master

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - node --version
  - npm install

script:
  - if [ "eslint-unit-tests-cov" == $CBTR_TEST ]; then node ./tests/unit/utils/static-srv.js & fi
  - if [ "eslint-unit-tests-cov" == $CBTR_TEST ]; then node ./tests/unit/utils/wait.js & fi
  - if [ "eslint-unit-tests-cov" != $CBTR_TEST ]; then node ./server.js & fi
  - if [ "eslint-unit-tests-cov" != $CBTR_TEST ]; then node ./server.js --native-runner --config tests/integration/conf/native/cbtr.json & fi
  - npm run $CBTR_TEST
