language: node_js

os:
  - linux
  - osx

node_js:
  - "stable"
  - "4.8"

env:
  - CBTR_TEST="functional-tests" TEST_TYPE="functional"
  - CBTR_TEST="integration-tests" TEST_TYPE="integration"
  - CBTR_TEST="eslint-unit-tests-1" TEST_TYPE="unit"
  - CBTR_TEST="unit-tests-2" TEST_TYPE="unit"
  - CBTR_TEST="unit-tests-3a" TEST_TYPE="unit"
  - CBTR_TEST="unit-tests-3b" TEST_TYPE="unit"

branches:
  only:
  - master

before_script:
  - if [ "unit" == "$TEST_TYPE" ]; then ./tests/unit/utils/static-srv.js & fi
  - if [ "unit" == "$TEST_TYPE" ]; then ./tests/unit/utils/wait.js & fi
  - if [ "functional" == "$TEST_TYPE" ]; then ./node_modules/.bin/istanbul instrument tests/functional/code/src/app.js > tests/functional/code/src/app.inst.js; fi
  - if [ "unit" != "$TEST_TYPE" ]; then ./node_modules/.bin/istanbul cover --handle-sigint --include-pid ./bin/server/server.js & fi
  - if [ "unit" != "$TEST_TYPE" ]; then ./node_modules/.bin/istanbul cover --handle-sigint --include-pid ./bin/server/server.js -- --native-runner --config tests/integration/conf/native/cbtr.json & fi

script:
  - npm run $CBTR_TEST

after_script:
  - if [ "unit" != "$TEST_TYPE" ]; then for server in `ps auxwww | grep "bin/server/server.js" | grep -v grep | awk '{print $2}'`; do kill -INT $server; sleep 2; done; fi
  - ./node_modules/.bin/istanbul report
  - npm run codecov-upload
  - npm run coveralls-upload
