language: node_js

os:
  - linux
  - osx

node_js:
  - "8"
  - "4"

env:
  - TEST="eslint-non-3rd-party" TYPE="unit"
  - TEST="core-scriptjob" TYPE="unit"
  - TEST="core-integration-tests" TYPE="integration"
  - TEST="core-functional-tests" TYPE="functional"
  - TEST="saucelabs-tunnel" TYPE="unit"
  - TEST="browserstack-tunnel" TYPE="unit"
  - TEST="crossbrowsertesting-tunnel" TYPE="unit"
  - TEST="saucelabs-scriptjob" TYPE="unit"
  - TEST="browserstack-scriptjob" TYPE="unit"
  - TEST="crossbrowsertesting-scriptjob" TYPE="unit"
  - TEST="saucelabs-job" TYPE="unit"
  - TEST="browserstack-job" TYPE="unit"
  - TEST="crossbrowsertesting-job" TYPE="unit"
  - TEST="saucelabs-platform-open" TYPE="unit"
  - TEST="browserstack-platform-open" TYPE="unit"
  - TEST="crossbrowsertesting-platform-open" TYPE="unit"
  - TEST="saucelabs-platform-job" TYPE="unit"
  - TEST="browserstack-platform-job" TYPE="unit"
  - TEST="crossbrowsertesting-platform-job" TYPE="unit"
  - TEST="saucelabs-platform-scriptjob" TYPE="unit"
  - TEST="browserstack-platform-scriptjob" TYPE="unit"
  - TEST="crossbrowsertesting-platform-scriptjob" TYPE="unit"
  - TEST="saucelabs-platform-status" TYPE="unit"
  - TEST="browserstack-platform-status" TYPE="unit"
  - TEST="crossbrowsertesting-platform-status" TYPE="unit"
  - TEST="saucelabs-platform-stop" TYPE="unit"
  - TEST="browserstack-platform-stop" TYPE="unit"
  - TEST="crossbrowsertesting-platform-stop" TYPE="unit"
  - TEST="saucelabs-platform-close" TYPE="unit"
  - TEST="browserstack-platform-close" TYPE="unit"
  - TEST="crossbrowsertesting-platform-close" TYPE="unit"
  - TEST="saucelabs-integration-tests" TYPE="integration"
  - TEST="browserstack-integration-tests" TYPE="integration"
  - TEST="crossbrowsertesting-integration-tests" TYPE="integration"
  - TEST="utils-saucelabs-tests" TYPE="functional"
  - TEST="utils-browserstack-tests" TYPE="functional"
  - TEST="utils-crossbrowsertesting-tests" TYPE="functional"
  - TEST="testem-saucelabs" TYPE="functional"
  - TEST="testem-browserstack" TYPE="functional"
  - TEST="testem-crossbrowsertesting" TYPE="functional"
  - TEST="native-runner-cases" TYPE="functional"
  - TEST="native-runner-retries" TYPE="functional"
  - TEST="native-runner-working" TYPE="functional"

branches:
  only:
  - master

before_script:
  - if [ "unit" == "$TYPE" ]; then ./tests/unit/utils/static-srv.js & fi
  - if [ "unit" == "$TYPE" ]; then ./tests/unit/utils/wait.js & fi
  - if [ "functional" == "$TYPE" ]; then ./node_modules/.bin/istanbul instrument tests/functional/code/src/app.js > tests/functional/code/src/app.inst.js; fi
  - if [ "unit" != "$TYPE" ]; then ./node_modules/.bin/istanbul cover --handle-sigint --include-pid ./bin/server/server.js & fi
  - if [ "integration" == "$TYPE" ]; then ./node_modules/.bin/istanbul cover --handle-sigint --include-pid ./bin/server/server.js -- --native-runner --config tests/integration/conf/native/cbtr.json & fi

script:
  - npm run $TEST

after_script:
  - if [ "unit" != "$TYPE" ]; then for server in `ps auxwww | grep "bin/server/server.js" | grep -v grep | awk '{print $2}'`; do kill -INT $server; sleep 2; done; fi
  - ./node_modules/.bin/istanbul report
  - npm run codecov-upload
  - npm run coveralls-upload

addons:
  hosts:
    - build.cross-browser-tests-runner.org
