environment:
  BROWSERSTACK_ACCESS_KEY:
    secure: EUWXxCOGMLebMQHSCTkdat1kCjm2IyRvmneOdF4r2To=
  BROWSERSTACK_USERNAME:
    secure: Jk/DEZv3lFCKevI5j+b/0Q==
  matrix:
  - nodejs_version: "4.2.0"
    cbtr_test: "eslint-unit-tests-win-1"
    is_unit_test: "true"
  - nodejs_version: "5.0.0"
    cbtr_test: "eslint-unit-tests-win-1"
    is_unit_test: "true"
  - nodejs_version: "6.9.0"
    cbtr_test: "eslint-unit-tests-win-1"
    is_unit_test: "true"
  - nodejs_version: "7.0.0"
    cbtr_test: "eslint-unit-tests-win-1"
    is_unit_test: "true"
  - nodejs_version: "8.0.0"
    cbtr_test: "eslint-unit-tests-win-1"
    is_unit_test: "true"
  - nodejs_version: "4.2.0"
    cbtr_test: "unit-tests-win-2"
    is_unit_test: "true"
  - nodejs_version: "5.0.0"
    cbtr_test: "unit-tests-win-2"
    is_unit_test: "true"
  - nodejs_version: "6.9.0"
    cbtr_test: "unit-tests-win-2"
    is_unit_test: "true"
  - nodejs_version: "7.0.0"
    cbtr_test: "unit-tests-win-2"
    is_unit_test: "true"
  - nodejs_version: "8.0.0"
    cbtr_test: "unit-tests-win-2"
    is_unit_test: "true"
  - nodejs_version: "4.2.0"
    cbtr_test: "integration-tests-win"
    is_unit_test: "false"
  - nodejs_version: "5.0.0"
    cbtr_test: "integration-tests-win"
    is_unit_test: "false"
  - nodejs_version: "6.9.0"
    cbtr_test: "integration-tests-win"
    is_unit_test: "false"
  - nodejs_version: "7.0.0"
    cbtr_test: "integration-tests-win"
    is_unit_test: "false"
  - nodejs_version: "8.0.0"
    cbtr_test: "integration-tests-win"
    is_unit_test: "false"
  - nodejs_version: "4.2.0"
    cbtr_test: "functional-tests-win"
    is_unit_test: "false"
  - nodejs_version: "5.0.0"
    cbtr_test: "functional-tests-win"
    is_unit_test: "false"
  - nodejs_version: "6.9.0"
    cbtr_test: "functional-tests-win"
    is_unit_test: "false"
  - nodejs_version: "7.0.0"
    cbtr_test: "functional-tests-win"
    is_unit_test: "false"
  - nodejs_version: "8.0.0"
    cbtr_test: "functional-tests-win"
    is_unit_test: "false"

branches:
  only:
  - master

skip_tags: true

max_jobs: 4

clone_depth: 50

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

before_test:
  - ps: $wait = Start-Process node .\tests\unit\utils\wait.js
  - ps: $staticsrv = Start-Process node .\tests\unit\utils\static-srv.js
  - ps: $server = Start-Process node .\bin\server\server.js
  - ps: $server = Start-Process node -ArgumentList ".\bin\server\server.js --native-runner --config tests\integration\conf\native\cbtr.json"

test_script:
  - npm run %cbtr_test%

after_test:
  - cmd: IF %is_unit_test%==true npm run codecov-upload

build: off

deploy: off
