environment:
  BROWSERSTACK_ACCESS_KEY:
    secure: EUWXxCOGMLebMQHSCTkdat1kCjm2IyRvmneOdF4r2To=
  BROWSERSTACK_USERNAME:
    secure: Jk/DEZv3lFCKevI5j+b/0Q==
  matrix:
  - nodejs_version: "7"
    cbtr_test: "eslint-unit-tests-codecov-win"
  - nodejs_version: "6"
    cbtr_test: "eslint-unit-tests-codecov-win"
  - nodejs_version: "7"
    cbtr_test: "integration-tests-win"
  - nodejs_version: "6"
    cbtr_test: "integration-tests-win"
  - nodejs_version: "7"
    cbtr_test: "functional-tests-win"
  - nodejs_version: "6"
    cbtr_test: "functional-tests-win"

matrix:
  fast_finish: true

branches:
  only:
  - master

skip_tags: true

max_jobs: 4

clone_depth: 50

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - copy /y .\etc\lib\codecov.js .\node_modules\codecov\lib

test_script:
  - ps: $wait = Start-Process node .\tests\unit\utils\wait.js
  - ps: $staticsrv = Start-Process node .\tests\unit\utils\static-srv.js
  - ps: $server = Start-Process node .\server.js
  - ps: $server = Start-Process node -ArgumentList ".\server.js --native-runner --config tests\integration\conf\native\cbtr.json"
  - npm run %cbtr_test%

build: off

deploy: off
