environment:
  nodejs_version: "6.10.2"
  BROWSERSTACK_ACCESS_KEY:
    secure: EUWXxCOGMLebMQHSCTkdat1kCjm2IyRvmneOdF4r2To=
  BROWSERSTACK_USERNAME:
    secure: Jk/DEZv3lFCKevI5j+b/0Q==

branches:
  only:
  - master

skip_tags: true

max_jobs: 4

clone_depth: 50

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - .\node_modules\.bin\eslint lib\
  - ps: $wait = Start-Process node .\tests\unit\utils\wait.js
  - .\node_modules\.bin\istanbul cover .\node_modules\mocha\bin\_mocha  -- --reporter lcovonly --ui bdd -R spec -t 5000 tests\unit
  - .\node_modules\.bin\codecov

build: off

deploy: off
