environment:
  BROWSERSTACK_ACCESS_KEY:
    secure: EUWXxCOGMLebMQHSCTkdat1kCjm2IyRvmneOdF4r2To=
  BROWSERSTACK_USERNAME:
    secure: Jk/DEZv3lFCKevI5j+b/0Q==
  matrix:
  - nodejs_version: "8"
    cbtr_test: "eslint-non-3rd-party-win"
  - nodejs_version: "8"
    cbtr_test: "browserstack-tunnel-win"
  - nodejs_version: "8"
    cbtr_test: "saucelabs-tunnel-win"
  - nodejs_version: "8"
    cbtr_test: "crossbrowsertesting-tunnel-win"
  - nodejs_version: "8"
    cbtr_test: "core-scriptjob-win"
  - nodejs_version: "8"
    cbtr_test: "browserstack-scriptjob-win"
  - nodejs_version: "8"
    cbtr_test: "saucelabs-scriptjob-win"
  - nodejs_version: "8"
    cbtr_test: "crossbrowsertesting-scriptjob-win"
  - nodejs_version: "8"
    cbtr_test: "browserstack-job-win"
  - nodejs_version: "8"
    cbtr_test: "saucelabs-job-win"
  - nodejs_version: "8"
    cbtr_test: "crossbrowsertesting-job-win"
  - nodejs_version: "8"
    cbtr_test: "browserstack-platform-win"
  - nodejs_version: "8"
    cbtr_test: "saucelabs-platform-win"
  - nodejs_version: "8"
    cbtr_test: "crossbrowsertesting-platform-win"
  - nodejs_version: "8"
    cbtr_test: "integration-tests-win"
  - nodejs_version: "8"
    cbtr_test: "utils-tests-win"
  - nodejs_version: "8"
    cbtr_test: "testem-win"
  - nodejs_version: "8"
    cbtr_test: "native-runner-win"
  - nodejs_version: "4"
    cbtr_test: "eslint-non-3rd-party-win"
  - nodejs_version: "4"
    cbtr_test: "browserstack-tunnel-win"
  - nodejs_version: "4"
    cbtr_test: "saucelabs-tunnel-win"
  - nodejs_version: "4"
    cbtr_test: "crossbrowsertesting-tunnel-win"
  - nodejs_version: "4"
    cbtr_test: "core-scriptjob-win"
  - nodejs_version: "4"
    cbtr_test: "browserstack-scriptjob-win"
  - nodejs_version: "4"
    cbtr_test: "saucelabs-scriptjob-win"
  - nodejs_version: "4"
    cbtr_test: "crossbrowsertesting-scriptjob-win"
  - nodejs_version: "4"
    cbtr_test: "browserstack-job-win"
  - nodejs_version: "4"
    cbtr_test: "saucelabs-job-win"
  - nodejs_version: "4"
    cbtr_test: "crossbrowsertesting-job-win"
  - nodejs_version: "4"
    cbtr_test: "browserstack-platform-win"
  - nodejs_version: "4"
    cbtr_test: "saucelabs-platform-win"
  - nodejs_version: "4"
    cbtr_test: "crossbrowsertesting-platform-win"
  - nodejs_version: "4"
    cbtr_test: "integration-tests-win"
  - nodejs_version: "4"
    cbtr_test: "utils-tests-win"
  - nodejs_version: "4"
    cbtr_test: "testem-win"
  - nodejs_version: "4"
    cbtr_test: "native-runner-win"

branches:
  only:
  - master

skip_tags: true

max_jobs: 1

clone_depth: 50

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
#  - copy /y .\etc\coveralls\bin\coveralls-win.js .\node_modules\coveralls\bin

before_test:
  - ps: $wait = Start-Process node .\tests\unit\utils\wait.js
  - ps: $staticsrv = Start-Process node .\tests\unit\utils\static-srv.js
  - ps: $server = Start-Process node .\bin\server\server.js
  - ps: $server = Start-Process node -ArgumentList ".\bin\server\server.js --native-runner --config tests\integration\conf\native\cbtr.json"

test_script:
  - npm run %cbtr_test%

after_test:
  - npm run codecov-upload
#  - npm run coveralls-upload-win

build: off

deploy: off

hosts:
  build.cross-browser-tests-runner.org: 127.0.0.1
