describe('Core', function() {
  require('./core/errors')
  require('./core/log')
  require('./core/env')
  require('./core/sleep')
  require('./core/settings')
  require('./core/options')
  require('./core/request')
  require('./core/process')
  require('./core/remotefile')
  require('./core/remotearchive')
})
