BrowserStack:
  JS:
    Windows:
      7:
        Chrome:
          - 32.0-36.0
          - "23.0"
    iOS:
      "6.0":
        Mobile Safari:
          - "iPad 3rd (6.0)"
          - "iPhone 4S (6.0)"
